#Put it in /etc/apache2/conf-enabled, remove example extention
#chmod entire path of project (especially .py files +x (better use /usr/share)

#following is example for a process called CP
WSGIDaemonProcess CP  user=www-data group=www-data processes=2 threads=15
WSGIPassAuthorization On
WSGIScriptAlias /cp /usr/share/nchs/cp/wsgi.py 
<Directory /usr/share/nchs/cp>
    WSGIProcessGroup CP
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
